# augmentation/preprocess setting
augmentation: 
  save_name: train_transform.yml


  # 들어간 것만 들어간 순서대로 적용. 세부 설정 원할경우 setting에 직접 적기
  # setting이나 list의 값은 꼭 augmentation_list.txt를 참고해서 넣어주세요
  # Resize, ToTensor, Normalize는 is_train과 관계 없이 default로 적용됩니다.
  # 적용 순서 : [Resize -> select -> Normalize -> ToTensor]
  select: [RandomBrightnessContrast, CoarseDropout, HorizontalFlip, ShiftScaleRotate, RandomSunFlare] 
  setting:
    Resize:
      height: 224
      width: 224

    RandomBrightnessContrast: # random brightness and contrast
      brightness_limit: 0.2
      contrast_limit: 0.2
      p: 0.5

    CoarseDropout: # random dropout
      max_height: 20
      max_holes: 5
      max_width: 20
      p: 0.5

    HorizontalFlip: #horizonttal flip
      p: 0.5

    RandomCrop: #random crop
      height: 200
      width: 200

    ShiftScaleRotate: #shift, scale, rotate
      p: 0.5
      rotate_limit: 20
      scale_limit: 0.1
      shift_limit: 0.05

    Normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
##############################################################################

# training setting
test_size: 0.2 # validation split rate
batch_size: 64
epochs: 1



# model
model_name: resnet18 # timm 모델명. timm_list.txt에 위치
model_type: timm # torchvision or timm
save_result_path: ./resnet18_test # 훈련 모델을 저장할 위치
is_pretrained: True # 사전 훈련 모델 여부


# optimizer
optimizer: 
  select: adamW
  adamW:
    name: adamW
    setting:
      lr: 0.001
      weight_decay: 0.01

  adam:
    name: adam
    setting:
      lr: 0.001
      weight_decay: 0.01
  
  SGD:
    name: SGD
    setting:
      lr: 0.001
      weight_decay: 0.01


# schedular
schedular:
  select: cosine # 해당 위치만 바꾸면 schedular 선택 가능합니다.

  cosine:
    name: cosine
    setting:
      T_max: 10 # 반주기가 10에폭
      eta_min: 0.00001 # min lr

  steplr:
    name: steplr
    setting:
      step_size: 30 # n step마다 lr 감소
      scheduler_gamma: 0.1 # lr감소 비율


# wandb 설정
project_name: 'local_test' # 프로젝트 이름
test_name: "resnet_test" # 해당 프로젝트 내 실험 이름



# 기본 경로 설정(한번 설정 후 바꿀 필요 없음)
traindata_dir: ../data/train # 훈련데이터가 위치한 폴더
traindata_info_file: ../data/train.csv # train image meta data가 들어있는 csv파일 위치
project_dir: "C:/Users/User/Desktop/naver_boostcamp/project/cv_05" #프로젝트 폴더


################################
# |-- data ( data folder )
# |   |-- sample_submission.csv
# |   |-- test
# |   |-- test.csv
# |   |-- train
# |   `-- train.csv
# |-- june21a ( project folder )
# |   |-- baseline_code
# |   |-- config
# |   |-- dataloader
# |   |-- infer.py
# |   |-- model
# |   |-- output.csv
# |   |-- requirements.txt
# |   |-- resnet101_result
# |   |-- resnet18_test
# |   |-- shared_codes
# |   |-- test.ipynb
# |   |-- timm_list.txt
# |   |-- train.py
# |   |-- util
# |   |-- vit_large_patch16_224_result
# |   `-- wandb