# augmentation을 추가시 다음을 수정해야함
# 1. 아래에 해당 augmentation의 hyperparameter 입력
# 2. augmentation table에 추가
# 3. dataloader.preprocess의 Albumentation에서 aug_transforms 리스트에 augmentation 추가 및 조건문 삽입
##########################################

# augmentation/preprocess setting
augmentation: 
  bright_contrast: # random brightness and contrast
    brightness_limit: 0.2
    contrast_limit: 0.2
    p: 0.5
  coarse_dropout: # random dropout
    max_height: 20
    max_holes: 5
    max_width: 20
    p: 0.5
  horizontal_flip: #horizonttal flip
    p: 0.5
  random_crop: #random crop
    height: 200
    width: 200
  shift_scale_rotate: #shift, scale, rotate
    p: 0.5
    rotate_limit: 20
    scale_limit: 0.1
    shift_limit: 0.05
  augmentation_table: # augmentation on/off를 위한 table
    bright_contrast: True
    coarse_dropout: True
    horizontal_flip: True
    random_crop: False
    shift_scale_rotate: True

image_size: !!python/tuple # size for resize
- 224
- 224


# training setting
test_size: 0.2 # validation split rate
batch_size: 64
epochs: 3



# model
model_name: resnet18 # timm 모델명. timm_list.txt에 위치
model_type: timm # torchvision or timm
save_result_path: ./resnet18_test # 훈련 모델을 저장할 위치
is_pretrained: True


# optimizer
optimizer: adamW  # ['adamW', 'adam', 'SGD']
learning_rate: 0.001
weight_decay: 0.01

# schedular
schedular_type: cosine # ['steplr'. 'cosine']



# 기본 경로 설정(한번 설정 후 바꿀 필요 없음)
traindata_dir: ../data/train # 훈련데이터가 위치한 폴더
traindata_info_file: ../data/train.csv # train image meta data가 들어있는 csv파일 위치
project_dir: "C:\Users\User\Desktop\네이버 부스트캠프\project\level1-imageclassification-cv-05" #프로젝트 폴더


# wandb 설정
project_name: 'sketch_classification example'
test_name: "resnet_test"


################################
# |-- data ( data folder )
# |   |-- sample_submission.csv
# |   |-- test
# |   |-- test.csv
# |   |-- train
# |   `-- train.csv
# |-- june21a ( project folder )
# |   |-- baseline_code
# |   |-- config
# |   |-- dataloader
# |   |-- infer.py
# |   |-- model
# |   |-- output.csv
# |   |-- requirements.txt
# |   |-- resnet101_result
# |   |-- resnet18_test
# |   |-- shared_codes
# |   |-- test.ipynb
# |   |-- timm_list.txt
# |   |-- train.py
# |   |-- util
# |   |-- vit_large_patch16_224_result
# |   `-- wandb